repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: run-pylint
        name: Run pylint
        entry: poetry run pylint test
        language: system
        types: [python]
      - id: run-pytest
        name: Run pytest
        entry: poetry run pytest
        language: system
        types: [python]
      - id: run-doctest
        name: Run doctest
        entry: poetry run python -m doctest -v life.py
        language: system
        types: [python]
